app-server:
  image: openenergy/app-server
  ports:
    - "5000:5000"
  environment:
   - MQTT=mosquitto
  links:
    - mosquitto
influx:
  image: tutum/influxdb:0.10
  volumes: #Mapping doesn't work, see https://github.com/influxdata/influxdb/issues/4425
    - ./data/influxdb:/data
  ports:
    - "8083:8083"
    - "8086:8086"
grafana:
  image: grafana/grafana
  ports:
    - "3000:3000"
  links:
    - influx
mosquitto:
  image: ansi/mosquitto
  ports:
    - "1883:1883"
node-red:
  image: openenergy/node-red
  hostname: op-en-node-red
  ports:
    - "1880:1880"
  volumes:
    - ./data/node-red:/root/.node-red
  links:
    - influx
    - mosquitto:mqtt
nginx:
  image: nginx
  ports:
    - "80:80"
  volumes:
    - ./data/www:/usr/share/nginx/html:ro
