app-server:
  image: openenergy/app-server
  ports:
    - "5000:5000"
  links:
    - mosquitto:mqtt
influx:
  image: influxdb
  volumes:
    - ./data/influxdb:/var/lib/influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
grafana:
  image: grafana/grafana
  volumes:
    - ./data/grafana:/var/lib/grafana
  ports:
    - "3000:3000"
  links:
    - influx
mosquitto:
  image: jllopis/mosquitto
  ports:
    - "1883:1883"
    - "9883:9883"
node-red:
  image: openenergy/node-red
  hostname: op-en-node-red
  ports:
    - "1880:1880"
  volumes:
    - ./data/node-red:/root/.node-red
  links:
    - influx
    - mosquitto:mqtt
nginx:
  image: nginx
  ports:
    - "80:80"
  volumes:
    - ./data/www:/usr/share/nginx/html:ro
    # We use a custom configuration to turn off sendfile. See https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/#virtualbox
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
